trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: BicepBuild@0
  inputs:
    process: 'single'
    sourceFile: '$(Build.SourcesDirectory)\AzureDeploy\AzureDeploy.bicep'
    stdout: false # Note if stdout is true 'outputDirectory' will not be interpreted
    outputFile: '$(Build.SourcesDirectory)\AzureDeploy\sample1.out.json' # Only when 'stdout' is false or not defined and 'outputDirectory' is empty or not defined

- task: CopyFiles@2
  displayName: 'Copy Deploy files'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/AzureDeploy/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- publish: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Publish pipeline artifacts'
  artifact: drop